"""Acceptance generation preserving the historical public behavior."""

import json
from pathlib import Path
import re
from typing import Any


def scenario_names(ir: dict[str, Any]) -> list[str]:
    """Return the exact unparameterized function names emitted by generate."""
    return [
        f"test_{index:03d}_{re.sub(r'[^a-z0-9_]+', '_', scenario['name'].lower()).strip('_')}"
        for index, scenario in enumerate(ir["scenarios"], 1)
    ]


def generate(ir: dict[str, Any], output: Path) -> Path:
    payload = json.dumps(ir, ensure_ascii=False)
    source = "\n".join(
        [
            "# Generated by wct accept generate. Do not edit.",
            "import json",
            "import os",
            "from pathlib import Path",
            "",
            "from tests.acceptance.steps import execute_scenario",
            "",
            "BASE_IR = json.loads(",
            f"    {payload!r}",
            ")",
            "",
            "",
            "def _ir():",
            '    path = os.environ.get("WCT_ACCEPT_IR")',
            '    return json.loads(Path(path).read_text(encoding="utf-8")) if path else BASE_IR',
            "",
        ]
    )
    source += "\n"
    for index, name in enumerate(scenario_names(ir), 1):
        source += f"""\ndef {name}():\n    execute_scenario(_ir(), {index - 1})\n"""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(source, encoding="utf-8")
    return output
