"""Orden de campos del vector payload_values por clase (SH-P03a/1 §3)."""

from tools.wct.evidence.pytest_payload_classes import (
    ChannelEnd,
    CollectedItem,
    CollectionEnd,
    CollectionReport,
    DeselectedItem,
    ExecutionEnd,
    ExecutionStart,
    InternalError,
    Interrupted,
    NodeDeclaration,
    OptionsClaim,
    PhaseLog,
    PhaseMake,
    PluginClaim,
    PluginsEnd,
    SelectedItem,
    SessionEnd,
    SessionEndError,
    SessionStart,
    TestEnd,
    TestStart,
)

WIRE_FIELDS: dict[type, tuple[str, ...]] = {
    NodeDeclaration: ("index", "nodeid"),
    ExecutionStart: ("argv", "cwd", "log_start", "monotonic_ns", "utc"),
    ChannelEnd: ("eof", "tail_bytes", "tail_sha256", "defect"),
    ExecutionEnd: (
        "exit_code",
        "termination",
        "signal",
        "log_end",
        "log_sha256",
        "monotonic_ns",
        "utc",
        "log_truncated",
    ),
    SessionStart: (
        "pytest_version",
        "pluggy_version",
        "observer_version",
        "runtime_profile_sha256",
    ),
    PluginClaim: ("name", "module", "distribution", "version", "source_sha256", "qualified"),
    PluginsEnd: ("count",),
    OptionsClaim: ("effective_sha256", "profile_match"),
    CollectedItem: ("nodeid", "property"),
    CollectionReport: ("nodeid", "outcome"),
    DeselectedItem: ("nodeid", "property"),
    SelectedItem: ("nodeid",),
    CollectionEnd: ("selected_count", "deselected_count"),
    TestStart: ("nodeid",),
    PhaseMake: (
        "nodeid",
        "phase",
        "outcome",
        "exception_present",
        "exception_type",
        "wasxfail",
        "xfail",
    ),
    PhaseLog: ("nodeid", "phase", "outcome", "wasxfail"),
    TestEnd: ("nodeid",),
    InternalError: ("exception_type",),
    Interrupted: ("exception_type",),
    SessionEnd: ("argument_exit", "observed_exit"),
    SessionEndError: ("exception_type",),
}
