"""Catálogo cerrado de event_code → origin/kind/clase (SH-P03a/1 §3)."""

from tools.wct.evidence.pytest_payload_classes import (
    ORIGIN_PYTEST,
    ORIGIN_SUPERVISOR,
    ChannelEnd,
    CollectedItem,
    CollectionEnd,
    CollectionReport,
    DeselectedItem,
    ExecutionEnd,
    ExecutionStart,
    InternalError,
    Interrupted,
    NodeDeclaration,
    OptionsClaim,
    PhaseLog,
    PhaseMake,
    PluginClaim,
    PluginsEnd,
    SelectedItem,
    SessionEnd,
    SessionEndError,
    SessionStart,
    TestEnd,
    TestStart,
)

EVENT_CATALOG: tuple[tuple[int, str, str, type], ...] = (
    (0, ORIGIN_SUPERVISOR, "node_declaration", NodeDeclaration),
    (1, ORIGIN_SUPERVISOR, "execution_start", ExecutionStart),
    (2, ORIGIN_SUPERVISOR, "channel_end", ChannelEnd),
    (3, ORIGIN_SUPERVISOR, "execution_end", ExecutionEnd),
    (4, ORIGIN_PYTEST, "session_start", SessionStart),
    (5, ORIGIN_PYTEST, "plugin", PluginClaim),
    (6, ORIGIN_PYTEST, "plugins_end", PluginsEnd),
    (7, ORIGIN_PYTEST, "options", OptionsClaim),
    (8, ORIGIN_PYTEST, "item", CollectedItem),
    (9, ORIGIN_PYTEST, "collect_report", CollectionReport),
    (10, ORIGIN_PYTEST, "deselected", DeselectedItem),
    (11, ORIGIN_PYTEST, "selected", SelectedItem),
    (12, ORIGIN_PYTEST, "collection_end", CollectionEnd),
    (13, ORIGIN_PYTEST, "test_start", TestStart),
    (14, ORIGIN_PYTEST, "phase_make", PhaseMake),
    (15, ORIGIN_PYTEST, "phase_log", PhaseLog),
    (16, ORIGIN_PYTEST, "test_end", TestEnd),
    (17, ORIGIN_PYTEST, "internal_error", InternalError),
    (18, ORIGIN_PYTEST, "interrupted", Interrupted),
    (19, ORIGIN_PYTEST, "session_end", SessionEnd),
    (20, ORIGIN_PYTEST, "session_end_error", SessionEndError),
)
