"""Builders de fixtures del selftest (fachada TEST-007)."""

from __future__ import annotations

from tools.wct.selftest.fixtures_adversarial import (  # reexport fachada TEST-007
    _CREDENTIAL_NAME_REGEX,
    _ORM_TYPES_REGEX,
    DEPS_PYPROJECT,
    F2_BILLING_ADVERSARY,
    F5_CLAMP_ADVERSARY,
    SECRET_PATHS,
    SEMGREP_RULES,
    _mutation_adversary,
    f2_a,
    f4_b,
    f6_a,
    f9_a,
    f10_a,
    f10_b,
    f12_a,
    f12_b,
)
from tools.wct.selftest.fixtures_git import (  # reexport fachada TEST-007
    COVERAGE_DIFF_MIN,
    _git_base,
    _git_track,
    f11_a,
    f11_b,
)
from tools.wct.selftest.fixtures_governance import (  # reexport fachada TEST-007
    IMPORT_LINTER,
    MUTMUT_PYPROJECT,
    VULTURE_MIN_CONFIDENCE,
    Builder,
    _arch_tree,
    _aws_secret_value,
    _plant,
    _private_key_block,
    _vulture_governance,
    f1_b,
    mutmut_pyproject,
)

BUILDERS: dict[str, Builder] = {
    "F1-b": f1_b,
    "F2-a": f2_a,
    "F2-b": F2_BILLING_ADVERSARY,
    "F4-b": f4_b,
    "F5-b": F5_CLAMP_ADVERSARY,
    "F6-a": f6_a,
    "F9-a": f9_a,
    "F10-a": f10_a,
    "F10-b": f10_b,
    "F11-a": f11_a,
    "F11-b": f11_b,
    "F12-a": f12_a,
    "F12-b": f12_b,
}

__all__ = [
    "BUILDERS",
    "COVERAGE_DIFF_MIN",
    "DEPS_PYPROJECT",
    "F2_BILLING_ADVERSARY",
    "F5_CLAMP_ADVERSARY",
    "IMPORT_LINTER",
    "MUTMUT_PYPROJECT",
    "SECRET_PATHS",
    "SEMGREP_RULES",
    "VULTURE_MIN_CONFIDENCE",
    "_CREDENTIAL_NAME_REGEX",
    "_ORM_TYPES_REGEX",
    "Builder",
    "_arch_tree",
    "_aws_secret_value",
    "_git_base",
    "_git_track",
    "_mutation_adversary",
    "_plant",
    "_private_key_block",
    "_vulture_governance",
    "f1_b",
    "f2_a",
    "f4_b",
    "f6_a",
    "f9_a",
    "f10_a",
    "f10_b",
    "f11_a",
    "f11_b",
    "f12_a",
    "f12_b",
    "mutmut_pyproject",
]
