from __future__ import annotations

from pathlib import Path
from typing import Any

from tools.wct.config import load_config, load_yaml

HEADER = "<!-- GENERATED BY `wct rules build`; DO NOT EDIT DIRECTLY. -->"


def rule_documents(root: Path) -> list[dict[str, Any]]:
    docs = [load_yaml(path) for path in sorted((root / "governance/rules").glob("*.yaml"))]
    return sorted(docs, key=lambda item: int(item.get("order", 0)))


def render(root: Path) -> str:
    _root, policy, _thresholds = load_config(root)
    lines = [HEADER, "", "# Write, Check, Trust (WCT) Contract", ""]
    lines.extend(
        [
            "These rules are provider-neutral. Commands and non-zero exit codes are authoritative.",
            f"Profile: `{policy['profile']}`. Run `uv run wct gate --tier fast` before handoff.",
            "",
        ]
    )
    for document in rule_documents(root):
        lines.extend([f"## {document['title']}", ""])
        for rule in document.get("rules", []):
            checks = ", ".join(rule.get("verified_by", ["human"]))
            text = " ".join(str(rule["text"]).split())
            lines.extend([f"- **{rule['id']}** — {text}", f"  Verified by: `{checks}`.", ""])
    return "\n".join(lines).rstrip() + "\n"


def targets(root: Path) -> list[Path]:
    _root, policy, _thresholds = load_config(root)
    return [root / provider["target"] for provider in policy.get("providers", [])]


def build(root: Path) -> list[Path]:
    content = render(root)
    written = []
    for path in targets(root):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


def drift(root: Path) -> list[Path]:
    expected = render(root)
    return [
        path
        for path in targets(root)
        if not path.is_file() or path.read_text(encoding="utf-8") != expected
    ]
